// Recognizable U.S. campuses used as name/place anchors. Stats are invented per prompt
// in synthesize.js — these coordinates only drive distance labels.
export const SCHOOL_POOL = [
  { id: 'pitt', name: 'University of Pittsburgh', city: 'Pittsburgh', state: 'PA', lat: 40.4406, lon: -79.9959, ownership: 'public', setting: 'city', size: 19000, tier: 'target' },
  { id: 'psu', name: 'Penn State University Park', city: 'State College', state: 'PA', lat: 40.7934, lon: -77.86, ownership: 'public', setting: 'town', size: 40000, tier: 'target' },
  { id: 'temple', name: 'Temple University', city: 'Philadelphia', state: 'PA', lat: 39.9812, lon: -75.1554, ownership: 'public', setting: 'city', size: 27000, tier: 'likely' },
  { id: 'drexel', name: 'Drexel University', city: 'Philadelphia', state: 'PA', lat: 39.9566, lon: -75.1899, ownership: 'private', setting: 'city', size: 14000, tier: 'likely' },
  { id: 'lehigh', name: 'Lehigh University', city: 'Bethlehem', state: 'PA', lat: 40.6259, lon: -75.3705, ownership: 'private', setting: 'suburban', size: 5000, tier: 'reach' },
  { id: 'cmu', name: 'Carnegie Mellon University', city: 'Pittsburgh', state: 'PA', lat: 40.4433, lon: -79.9436, ownership: 'private', setting: 'city', size: 7000, tier: 'reach' },
  { id: 'wcu', name: 'West Chester University of Pennsylvania', city: 'West Chester', state: 'PA', lat: 39.9601, lon: -75.6052, ownership: 'public', setting: 'suburban', size: 17000, tier: 'likely' },
  { id: 'millersville', name: 'Millersville University', city: 'Millersville', state: 'PA', lat: 39.9979, lon: -76.3541, ownership: 'public', setting: 'town', size: 6000, tier: 'likely' },
  { id: 'rutgers', name: 'Rutgers University–New Brunswick', city: 'New Brunswick', state: 'NJ', lat: 40.5006, lon: -74.4474, ownership: 'public', setting: 'city', size: 36000, tier: 'target' },
  { id: 'udel', name: 'University of Delaware', city: 'Newark', state: 'DE', lat: 39.6777, lon: -75.7506, ownership: 'public', setting: 'suburban', size: 18000, tier: 'target' },
  { id: 'nyu', name: 'New York University', city: 'New York', state: 'NY', lat: 40.7295, lon: -73.9965, ownership: 'private', setting: 'city', size: 26000, tier: 'reach' },
  { id: 'cornell', name: 'Cornell University', city: 'Ithaca', state: 'NY', lat: 42.4534, lon: -76.4735, ownership: 'private', setting: 'town', size: 15000, tier: 'reach' },
  { id: 'rit', name: 'Rochester Institute of Technology', city: 'Rochester', state: 'NY', lat: 43.0848, lon: -77.6744, ownership: 'private', setting: 'suburban', size: 14000, tier: 'target' },
  { id: 'northeastern', name: 'Northeastern University', city: 'Boston', state: 'MA', lat: 42.3398, lon: -71.0892, ownership: 'private', setting: 'city', size: 15000, tier: 'reach' },
  { id: 'bu', name: 'Boston University', city: 'Boston', state: 'MA', lat: 42.3505, lon: -71.1054, ownership: 'private', setting: 'city', size: 18000, tier: 'target' },
  { id: 'usc', name: 'University of Southern California', city: 'Los Angeles', state: 'CA', lat: 34.0224, lon: -118.2851, ownership: 'private', setting: 'city', size: 21000, tier: 'reach' },
  { id: 'ucla', name: 'University of California, Los Angeles', city: 'Los Angeles', state: 'CA', lat: 34.0689, lon: -118.4452, ownership: 'public', setting: 'city', size: 32000, tier: 'reach' },
  { id: 'ucsd', name: 'University of California, San Diego', city: 'La Jolla', state: 'CA', lat: 32.8801, lon: -117.234, ownership: 'public', setting: 'suburban', size: 33000, tier: 'target' },
  { id: 'calpoly', name: 'California Polytechnic State University', city: 'San Luis Obispo', state: 'CA', lat: 35.305, lon: -120.6625, ownership: 'public', setting: 'town', size: 21000, tier: 'target' },
  { id: 'michigan', name: 'University of Michigan', city: 'Ann Arbor', state: 'MI', lat: 42.278, lon: -83.7382, ownership: 'public', setting: 'city', size: 32000, tier: 'reach' },
  { id: 'osu', name: 'Ohio State University', city: 'Columbus', state: 'OH', lat: 40.0067, lon: -83.0305, ownership: 'public', setting: 'city', size: 46000, tier: 'target' },
  { id: 'utaustin', name: 'University of Texas at Austin', city: 'Austin', state: 'TX', lat: 30.2849, lon: -97.7341, ownership: 'public', setting: 'city', size: 40000, tier: 'reach' },
  { id: 'rice', name: 'Rice University', city: 'Houston', state: 'TX', lat: 29.7174, lon: -95.4018, ownership: 'private', setting: 'city', size: 4000, tier: 'reach' },
  { id: 'uf', name: 'University of Florida', city: 'Gainesville', state: 'FL', lat: 29.6436, lon: -82.3549, ownership: 'public', setting: 'city', size: 35000, tier: 'target' },
  { id: 'miami', name: 'University of Miami', city: 'Coral Gables', state: 'FL', lat: 25.7217, lon: -80.2793, ownership: 'private', setting: 'suburban', size: 12000, tier: 'target' },
  { id: 'usf', name: 'University of South Florida', city: 'Tampa', state: 'FL', lat: 28.0587, lon: -82.4139, ownership: 'public', setting: 'city', size: 30000, tier: 'likely' },
  { id: 'gatech', name: 'Georgia Institute of Technology', city: 'Atlanta', state: 'GA', lat: 33.7756, lon: -84.3963, ownership: 'public', setting: 'city', size: 17000, tier: 'reach' },
  { id: 'emory', name: 'Emory University', city: 'Atlanta', state: 'GA', lat: 33.7971, lon: -84.3232, ownership: 'private', setting: 'suburban', size: 7000, tier: 'reach' },
  { id: 'unc', name: 'University of North Carolina at Chapel Hill', city: 'Chapel Hill', state: 'NC', lat: 35.9049, lon: -79.0469, ownership: 'public', setting: 'town', size: 20000, tier: 'target' },
  { id: 'uw', name: 'University of Washington', city: 'Seattle', state: 'WA', lat: 47.6553, lon: -122.3035, ownership: 'public', setting: 'city', size: 32000, tier: 'target' },
  { id: 'cu', name: 'University of Colorado Boulder', city: 'Boulder', state: 'CO', lat: 40.0076, lon: -105.2659, ownership: 'public', setting: 'city', size: 30000, tier: 'target' },
  { id: 'utah', name: 'University of Utah', city: 'Salt Lake City', state: 'UT', lat: 40.7649, lon: -111.8421, ownership: 'public', setting: 'city', size: 25000, tier: 'target' },
  { id: 'uvm', name: 'University of Vermont', city: 'Burlington', state: 'VT', lat: 44.4778, lon: -73.1965, ownership: 'public', setting: 'town', size: 11000, tier: 'target' },
  { id: 'uoregon', name: 'University of Oregon', city: 'Eugene', state: 'OR', lat: 44.0448, lon: -123.0726, ownership: 'public', setting: 'city', size: 22000, tier: 'target' },
  { id: 'illinois', name: 'University of Illinois Urbana-Champaign', city: 'Champaign', state: 'IL', lat: 40.102, lon: -88.2272, ownership: 'public', setting: 'city', size: 35000, tier: 'target' },
  { id: 'arizona', name: 'Arizona State University', city: 'Tempe', state: 'AZ', lat: 33.4242, lon: -111.9281, ownership: 'public', setting: 'city', size: 55000, tier: 'likely' },
  { id: 'howard', name: 'Howard University', city: 'Washington', state: 'DC', lat: 38.9227, lon: -77.0214, ownership: 'private', setting: 'city', size: 10000, tier: 'target' },
]
